# frozen_string_literal: true
# Gemfile for testing puppet modules with test-kitchen
source 'https://rubygems.org'

gem 'rake'
gem 'serverspec'
gem 'puppet'
gem 'librarian-puppet'
gem 'test-kitchen'
gem 'kitchen-puppet' # provisioner driver for test-kitchen
gem 'kitchen-docker'
gem 'kitchen-config'
gem 'kitchen-verifier-serverspec'
gem 'net-ssh'
gem 'rspec'
gem 'rspec-puppet'
gem 'rubocop'
gem 'metadata-json-lint'
gem 'puppet-lint'
gem 'facter'
gem 'puppetlabs_spec_helper'
